apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - privileged-rolebinding.yaml

images:
  - name: ghcr.io/hanzos3/csi-node-driver-registrar
    newName: registry.redhat.io/openshift4/ose-csi-node-driver-registrar-rhel8
    digest: sha256:9006d4a80df02b51102961e70e55ae08e2757fc4c62d3c2605b8ffed3a344e8d

  - name: ghcr.io/hanzos3/livenessprobe
    newName: registry.redhat.io/openshift4/ose-csi-livenessprobe-rhel8
    digest: sha256:9309cf88631e1cbb5362081a65f2de752cc130d231e8ba2bdd9ef640b51a6b66

  - name: ghcr.io/hanzos3/csi-provisioner
    newName: registry.redhat.io/openshift4/ose-csi-external-provisioner-rhel8
    digest: sha256:ffc107c70d24eb86d2120d4bce217bcfebb46694817217f134ead9e9b72d2ff3

  - name: ghcr.io/hanzos3/csi-resizer
    newName: registry.redhat.io/openshift4/ose-csi-external-resizer-rhel8
    digest: sha256:ed845b49de7e1c363bc8e8485a04288c03125a3cff7c7f100d35b5b88645725a
